# Generated by Django 3.2.9 on 2021-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('authors', models.CharField(max_length=100)),
                ('number_of_pages', models.CharField(max_length=10)),
                ('publisher', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
            ],
        ),
    ]
